### ISSUE TITLE
error got 400 when fetching stories

### ISSUE THREAD

**Issue by orhanoz** [hoschiCZ/instastories-backup#2]
hi i trying your script but keep getting 400 status code any idea on how to solve it ?

here is the output :
python3 main.py 
Loading new entries to DB
ERROR: got 400 when fetching stories entries!
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    for item in response['items']:
KeyError: 'items'

**Comment by ondrejsojka** [comment]
Everything works for me, maybe check your cookies if they're still valid?

**Comment by ondrejsojka** [comment]
Suddenly the same error happened to me too. Will investigate.

**Comment by ondrejsojka** [comment]
To resolve this problem, as the last entry in `headers` in `prefs.json`, add the line `x-ig-capabilities": "36oD"`.
