### ISSUE TITLE
sqlite3.DatabaseError: file is encrypted or is not a database

### ISSUE THREAD

**Issue by Retul15** [hoschiCZ/instastories-backup#3]
It worked fine few weeks. But now I'm getting this error.
`Traceback (most recent call last):
  File "main.py", line 16, in <module>
    c.execute("CREATE TABLE IF NOT EXISTS `entries` (`id`       TEXT UNIQUE, `url`   TEXT, `userid`  TEXT, `username` TEXT, `taken_at` INTEGER, `filename` TEXT);")
sqlite3.DatabaseError: file is encrypted or is not a database`

**Comment by ondrejsojka** [comment]
From the error message, it seems like database is corrupted.

The program saves data about which files it has already downloaded and some additional metadata into a file named stories.sqlite3. It should be safe to delete it, you will not lose your backed up photos and videos.
