### ISSUE TITLE
Unable to get user ID after API change by IG

### ISSUE THREAD

**Issue by zenyusy** [hoschiCZ/instastories-backup#6]
https://www.instagram.com/username/?__a=1 returns HTTP ERROR 403 without proper **user-specific** header/cookie settings  (one header setting for one user seems not working for another).

i compared 2 different `/?__a=1` requests and there were at least 3 key/value pairs changed, among which `x-instagram-gis` in the header might be crucial.

is this due to some  API change by Ins. ?

**Comment by ondrejsojka** [comment]
I have been able to reproduce. The fix will be to use the session we get after logging in to fetch user IDs.

**Comment by zenyusy** [comment]
the session should have correct `x-instagram-gis` set in the header. 
see https://github.com/jlobos/instagram-web-api/issues/30

**Comment by ondrejsojka** [comment]
I do not currently have time for fixing this, so this will have to wait. What about fixing this by fetching instagram.com/username (this will never get blocked), regexing to get window._shareddata and getting id from there?
